version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - python -m pip install poetry
      - python -m poetry config virtualenvs.create false
      - python -m poetry install -E docs
      - pip list
      - poetry show
