version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - which python
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -E docs
      - pip list
      - poetry show
